server:
  port: 8761
  address: localhost

spring:
  application:
    name: naming-server
  datasource:
    tomcat:
      url:

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/